apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx-app
  ports:
    - port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.port }}
      nodePort: {{ .Values.service.nginxNodePort }}

---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: node-app
  ports:
    - port: {{ .Values.node.port }}
      targetPort: {{ .Values.node.port }}
      nodePort: {{ .Values.service.nodeNodePort }}
