apiVersion: apps/v1
kind: Deployment
metadata:
  name: devnode-deployment
  labels:
    app: devnode-app
spec:
  replicaSet: 2
  selector:
    matchLabels:
      app: devnode-app
  template:
    metadata:
      labels:
        app: devnode-app
    spec:
      containers:
      - name: node-container
        image: custom-node:latest
        ports:
        - containerPort: 3000
